sudo: false
language: python
python:
  - 3.6.2
services:
  - postgresql
before_script:
  - psql -c 'create database shl_test;' -U postgres
script:
  - nosetests -sv --with-coverage tests/ app/auth/tests/ app/shopping_list/tests
after_success:
  - coveralls
