from app import API


BASE_PREFIX = API.prefix


GET_SHOPPINGLIST_PREFIX = 'shopping-lists'
GET_SHOPPINGLIST_DETAIL_PREFIX = 'shopping-lists/'

CREATE_SHOPPINGLIST_URL = BASE_PREFIX + GET_SHOPPINGLIST_PREFIX
GET_SHOPPINGLISTS_URL = BASE_PREFIX + GET_SHOPPINGLIST_PREFIX
GET_SHOPPINGLIST_DETAIL_URL = BASE_PREFIX + GET_SHOPPINGLIST_DETAIL_PREFIX
UPDATE_SHOPPINGLIST_URL = BASE_PREFIX + GET_SHOPPINGLIST_DETAIL_PREFIX


__all__ = [
    CREATE_SHOPPINGLIST_URL, GET_SHOPPINGLISTS_URL, GET_SHOPPINGLIST_DETAIL_URL, UPDATE_SHOPPINGLIST_URL
]
